@extends('layouts.admin')
@section('title', 'Dashboard | Wonder Godoro Point')
@section('content')
@php
    use App\Models\Customer; use App\Models\Conversation; use App\Models\Message; use App\Models\Order; use App\Models\Product;
    $totalOrders=Order::count(); $totalSales=Order::where('payment_status','paid')->sum('total_amount');
    $newCustomers=Customer::where('status','new')->count(); $pendingOrders=Order::whereIn('status',['pending','processing'])->count();
    $todayOrders=Order::whereDate('ordered_at',today())->count(); $todaySales=Order::whereDate('ordered_at',today())->where('payment_status','paid')->sum('total_amount');
    $pendingPayments=Order::whereIn('payment_status',['unpaid','partial'])->sum('total_amount'); $pendingDeliveries=Order::whereIn('delivery_status',['pending','processing'])->count();
    $unreadMessages=Message::where('direction','inbound')->whereNull('read_at')->count(); $openConversations=Conversation::where('status','open')->count();
    $lowStockProducts=Product::where('is_active',true)->whereColumn('stock_quantity','<=','reorder_level')->count();
    $salesTarget=(float) env('WGP_SALES_TARGET',0); $targetPct=$salesTarget>0?min(100,round(($todaySales/$salesTarget)*100)):0;
    $days=[]; $maxSales=1;
    for($i=6;$i>=0;$i--){$d=now()->subDays($i);$v=(float)Order::whereDate('ordered_at',$d)->where('payment_status','paid')->sum('total_amount');$days[]=['label'=>$d->format('D'),'value'=>$v];$maxSales=max($maxSales,$v);}
    $points=[]; foreach($days as $i=>$d){$x=30+($i*(640/6));$y=180-(($d['value']/$maxSales)*135);$points[]=round($x,1).','.round($y,1);} $poly=implode(' ',$points);
    $topProducts=Order::selectRaw('product_name, SUM(quantity) qty, SUM(total_amount) revenue')->groupBy('product_name')->orderByDesc('qty')->limit(5)->get();
    $maxQty=max(1,(int)($topProducts->max('qty')??1));
    $recentOrders=Order::with('customer')->latest('ordered_at')->limit(5)->get();
    $greeting=now()->hour<12?'Good morning':(now()->hour<17?'Good afternoon':(now()->hour<21?'Good evening':'Good night'));
@endphp
<header class="dashboard-topbar"><div><p class="auth-kicker">WONDER GODORO POINT</p><h1>{{ $greeting }}, {{ auth()->user()->name }}</h1></div><span class="dashboard-date">{{ now()->format('D, M j, Y') }}</span></header>
<section class="dashboard-welcome"><div><p class="dashboard-section-kicker">Store overview</p><h2>Welcome back! Here is your store overview.</h2><p>Track sales, customers, orders and delivery activity from one workspace.</p></div><a class="dashboard-primary-action" href="{{ route('admin.orders.create') }}">New Order <span>+</span></a></section>
<section class="wgp-dashboard-grid">
<div class="wgp-panel"><div class="wgp-panel-head"><div><div class="wgp-panel-title">Sales Overview</div><span class="wgp-panel-sub">Paid sales for the last 7 days</span></div><select class="wgp-select" aria-label="Sales period"><option>This Week</option></select></div><div class="wgp-chart"><svg viewBox="0 0 700 220" role="img" aria-label="Seven day sales chart"><defs><linearGradient id="wgpArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#d6a62d" stop-opacity=".30"/><stop offset="100%" stop-color="#d6a62d" stop-opacity=".02"/></linearGradient></defs><line x1="30" y1="45" x2="670" y2="45" class="wgp-chart-grid"/><line x1="30" y1="90" x2="670" y2="90" class="wgp-chart-grid"/><line x1="30" y1="135" x2="670" y2="135" class="wgp-chart-grid"/><line x1="30" y1="180" x2="670" y2="180" class="wgp-chart-grid"/><polygon points="30,180 {{ $poly }} 670,180" class="wgp-chart-area"/><polyline points="{{ $poly }}" class="wgp-chart-line"/>@foreach($days as $i=>$d) @php $x=30+($i*(640/6)); $y=180-(($d['value']/$maxSales)*135); @endphp <circle cx="{{ $x }}" cy="{{ $y }}" r="4" class="wgp-chart-dot"/><text x="{{ $x }}" y="205" text-anchor="middle" class="wgp-axis">{{ $d['label'] }}</text>@endforeach</svg></div></div>
<div class="wgp-panel"><div class="wgp-panel-head"><div><div class="wgp-panel-title">Top Products</div><span class="wgp-panel-sub">By units sold</span></div><a href="{{ route('admin.products.index') }}" class="wgp-panel-sub">View all →</a></div><div class="wgp-top-products">@forelse($topProducts as $p)<div class="wgp-product-row"><div class="wgp-product-thumb"></div><div class="wgp-product-meta"><strong>{{ $p->product_name ?: 'Product' }}</strong><small>{{ $p->qty }} orders · TSh {{ number_format($p->revenue,0) }}</small></div><div class="wgp-product-bar"><span style="width:{{ min(100,($p->qty/$maxQty)*100) }}%"></span></div></div>@empty<div style="padding:2rem 0;color:#8995a5;font-size:.68rem;text-align:center">No product sales yet.</div>@endforelse</div></div>
</section>
<section class="dashboard-module-section" style="margin-top:1rem"><div class="dashboard-section-heading"><div><p class="dashboard-section-kicker">Business Operations</p><h2>Today at a glance</h2></div><a href="{{ route('admin.reports.index') }}" class="dashboard-module-count">Sales & Reports →</a></div><div style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-top:12px">
@php $metrics=[['Today Sales','TSh '.number_format($todaySales,0),'↑',$todaySales? 'Paid today':'No paid sales',route('admin.reports.index')],['Today Orders',$todayOrders,'','Orders placed today',route('admin.orders.index')],['Pending Payments','TSh '.number_format($pendingPayments,0),'','Unpaid + partial',route('admin.orders.index')],['Pending Deliveries',$pendingDeliveries,'','Awaiting delivery',route('admin.delivery.index')],['Sales Target',$salesTarget>0?$targetPct.'%':'Not set','','Target: TSh '.number_format($salesTarget,0),route('admin.reports.index')]]; @endphp
@foreach($metrics as $m)<a href="{{ $m[4] }}" class="wgp-kpi"><span>{{ $m[0] }}</span><strong>{{ $m[1] }}</strong><small>{{ $m[3] }}</small>@if($m[0]==='Sales Target' && $salesTarget>0)<i><b style="width:{{ $targetPct }}%"></b></i>@endif</a>@endforeach</div></section>
<section class="dashboard-module-section" style="margin-top:1rem"><div class="dashboard-section-heading"><div><p class="dashboard-section-kicker">Order management</p><h2>Recent Orders</h2></div><a href="{{ route('admin.orders.index') }}" class="dashboard-module-count">View all →</a></div><div class="wgp-table-wrap" style="margin-top:12px"><table class="wgp-table"><thead><tr><th>#</th><th>Customer</th><th>Product</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td>{{ $order->order_number }}</td><td><div class="wgp-customer-name"><span class="wgp-avatar">{{ str($order->customer?->name ?: 'C')->substr(0,1)->upper() }}</span><span><strong>{{ $order->customer?->name ?: 'Customer' }}</strong><small>{{ $order->customer?->phone ?: 'No phone' }}</small></span></div></td><td>{{ $order->product_name }}{{ $order->product_size?' ('.$order->product_size.')':'' }}</td><td><strong>TSh {{ number_format($order->total_amount,0) }}</strong></td><td><span class="wgp-status wgp-status-{{ $order->status==='completed'?'won':($order->status==='cancelled'?'lost':'new') }}">{{ ucfirst($order->status) }}</span></td><td>{{ optional($order->ordered_at)->format('M j, H:i') }}</td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:2rem;color:#8995a5">No orders yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="dashboard-module-section" style="margin-top:1rem"><div class="dashboard-section-heading"><div><p class="dashboard-section-kicker">CRM</p><h2>Key signals</h2></div></div><div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:12px"><a href="{{ route('admin.customers.index') }}" class="wgp-kpi"><span>Total Customers</span><strong data-counter="{{ Customer::count() }}">0</strong><small>Customer database</small></a><a href="{{ route('admin.inbox') }}" class="wgp-kpi"><span>Unread Messages</span><strong data-counter="{{ $unreadMessages }}">0</strong><small>Needs attention</small></a><a href="{{ route('admin.inbox') }}" class="wgp-kpi"><span>Open Conversations</span><strong data-counter="{{ $openConversations }}">0</strong><small>Active chats</small></a><a href="{{ route('admin.products.index') }}" class="wgp-kpi"><span>Low Stock</span><strong data-counter="{{ $lowStockProducts }}">0</strong><small>Reorder alerts</small></a></div></section>
@endsection
