@extends('layouts.admin')
@section('title', $product->name.' | Wonder Godoro Point')
@push('styles')
<style>
.product-page{max-width:1050px;margin:0 auto;padding:32px}.product-head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.product-head h1{margin:0;font-size:32px}.product-head p{margin:6px 0 0;color:#737373}.product-card{background:#fff;border:1px solid #e7e2d9;border-radius:16px;padding:26px;box-shadow:0 8px 25px rgba(0,0,0,.04)}.product-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.product-stat{padding:18px;border:1px solid #eee7dc;border-radius:12px;background:#faf9f6}.product-stat span{display:block;font-size:12px;color:#777}.product-stat strong{display:block;font-size:23px;margin-top:6px}.product-description{margin-top:24px;padding-top:24px;border-top:1px solid #eee}.product-btn{display:inline-flex;padding:11px 17px;border-radius:9px;text-decoration:none;font-weight:700;border:1px solid #ddd;background:#fff;color:#333}.product-btn-primary{background:#171717;color:#fff;border-color:#171717}@media(max-width:800px){.product-page{padding:20px 14px}.product-head{align-items:flex-start;flex-direction:column}.product-stats{grid-template-columns:repeat(2,1fr)}}
</style>
@endpush
@section('content')
<div class="product-page"><div class="product-head"><div><h1>{{ $product->name }}</h1><p>{{ $product->category?->name ?? 'Uncategorised' }} · {{ $product->size ?: 'Standard' }}</p></div><div style="display:flex;gap:8px"><a class="product-btn" href="{{ route('admin.products.index') }}">Products</a><a class="product-btn product-btn-primary" href="{{ route('admin.products.edit', $product) }}">Edit</a></div></div><div class="product-card">@if($product->image_path)<div class="wgp-product-hero-image"><img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}"></div>@endif<div class="product-stats"><div class="product-stat"><span>Selling price</span><strong>TSh {{ number_format($product->price,0) }}</strong></div><div class="product-stat"><span>Cost price</span><strong>TSh {{ number_format($product->cost_price,0) }}</strong></div><div class="product-stat"><span>Stock</span><strong>{{ $product->stock_quantity }}</strong></div><div class="product-stat"><span>SKU</span><strong>{{ $product->sku ?: '—' }}</strong></div></div><div class="product-description"><strong>Description</strong><p>{{ $product->description ?: 'No description has been added.' }}</p></div></div></div>
@endsection
