@extends('layouts.admin')
@section('title', 'Delivery | Wonder Godoro Point')
@push('styles')
<style>
.delivery-page{max-width:1250px;margin:0 auto;padding:32px}.delivery-head{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:22px}.delivery-head h1{margin:0;font-size:32px}.delivery-head p{margin:6px 0 0;color:#737373}.delivery-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.delivery-tab{padding:9px 13px;border:1px solid #ddd;border-radius:9px;text-decoration:none;color:#444;background:#fff;font-size:13px}.delivery-tab.active{background:#171717;color:#fff;border-color:#171717}.delivery-table{background:#fff;border:1px solid #e7e2d9;border-radius:14px;overflow:auto}.delivery-table table{width:100%;border-collapse:collapse;min-width:950px}.delivery-table th,.delivery-table td{padding:14px 15px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.delivery-table th{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#777}.delivery-form{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px;align-items:center}.delivery-form select,.delivery-form input{padding:8px;border:1px solid #ddd;border-radius:7px}.delivery-form button{padding:8px 12px;border:0;border-radius:7px;background:#171717;color:#fff;font-weight:700}.delivery-status{font-weight:700;text-transform:capitalize}.delivery-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.delivery-stat{background:#fff;border:1px solid #e7e2d9;border-radius:12px;padding:16px}.delivery-stat span{display:block;color:#777;font-size:12px}.delivery-stat strong{display:block;font-size:25px;margin-top:5px}@media(max-width:800px){.delivery-page{padding:20px 14px}.delivery-head{align-items:flex-start;flex-direction:column}.delivery-summary{grid-template-columns:repeat(2,1fr)}}
</style>
@endpush
@section('content')
<div class="delivery-page">
    <div class="delivery-head"><div><h1>Delivery</h1><p>Move orders from pending to assigned, out for delivery and delivered.</p></div><a class="delivery-tab" href="{{ route('admin.orders.index') }}">View Orders →</a></div>
    <div class="delivery-summary">@foreach(['pending','processing','delivered','cancelled'] as $key)<div class="delivery-stat"><span>{{ ucfirst($key) }}</span><strong>{{ $counts[$key] ?? 0 }}</strong></div>@endforeach</div>
    <div class="delivery-tabs">@foreach(['pending','processing','delivered','cancelled'] as $key)<a class="delivery-tab {{ $status===$key?'active':'' }}" href="{{ route('admin.delivery.index',['status'=>$key]) }}">{{ ucfirst($key) }}</a>@endforeach</div>
    <div class="delivery-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Address</th><th>Update</th></tr></thead><tbody>
    @forelse($orders as $order)<tr><td><strong>{{ $order->order_number }}</strong><br><small>TSh {{ number_format($order->total_amount,0) }}</small></td><td>{{ $order->customer?->name }}<br><small>{{ $order->customer?->phone }}</small></td><td>{{ $order->product_name }}<br><small>{{ $order->product_size }}</small></td><td>{{ $order->delivery_area ?: '—' }}<br><small>{{ $order->delivery_address ?: 'No address' }}</small></td><td><form class="delivery-form" method="POST" action="{{ route('admin.delivery.orders.update',$order) }}">@csrf @method('PATCH')<select name="delivery_status"><option value="pending" @selected($order->delivery_status==='pending')>Pending</option><option value="processing" @selected($order->delivery_status==='processing')>Processing</option><option value="delivered" @selected($order->delivery_status==='delivered')>Delivered</option><option value="cancelled" @selected($order->delivery_status==='cancelled')>Cancelled</option></select><select name="delivery_assigned_to"><option value="">Unassigned</option>@foreach($drivers as $driver)<option value="{{ $driver->id }}" @selected($order->delivery_assigned_to==$driver->id)>{{ $driver->name }}</option>@endforeach</select><input name="delivery_area" value="{{ $order->delivery_area }}" placeholder="Area"><button type="submit">Save</button></form></td></tr>@empty<tr><td colspan="5">No delivery orders in this status.</td></tr>@endforelse
    </tbody></table></div>
    <div style="margin-top:18px">{{ $orders->links() }}</div>
</div>
@endsection
