@extends('layouts.admin')
@section('title', 'Reports | Wonder Godoro Point')
@push('styles')
<style>
.report-page{max-width:1200px;margin:0 auto;padding:32px}.report-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:22px}.report-head h1{margin:0;font-size:32px}.report-head p{margin:6px 0 0;color:#737373}.report-filter{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.report-filter label{display:flex;flex-direction:column;gap:5px;font-size:11px;font-weight:700;color:#666}.report-filter input{padding:9px;border:1px solid #ddd;border-radius:8px}.report-filter button{padding:10px 14px;border:0;border-radius:8px;background:#171717;color:#fff;font-weight:700}.report-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.report-card{background:#fff;border:1px solid #e7e2d9;border-radius:14px;padding:18px}.report-card span{display:block;font-size:12px;color:#777}.report-card strong{display:block;font-size:24px;margin-top:6px}.report-panel{margin-top:18px;background:#fff;border:1px solid #e7e2d9;border-radius:14px;padding:20px}.report-panel h2{margin:0 0 15px;font-size:18px}.report-table{width:100%;border-collapse:collapse}.report-table th,.report-table td{padding:11px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.report-table th{font-size:11px;text-transform:uppercase;color:#777}@media(max-width:900px){.report-grid{grid-template-columns:repeat(2,1fr)}.report-head{align-items:flex-start;flex-direction:column}}@media(max-width:500px){.report-grid{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
<div class="report-page">
    <div class="report-head"><div><h1>Reports</h1><p>Sales, orders, customer activity, delivery and estimated gross profit.</p></div><form class="report-filter"><label>From<input type="date" name="from" value="{{ $data['from']->format('Y-m-d') }}"></label><label>To<input type="date" name="to" value="{{ $data['to']->format('Y-m-d') }}"></label><button>Apply</button></form></div>
    <div class="report-grid"><div class="report-card"><span>Revenue</span><strong>TSh {{ number_format($data['revenue'],0) }}</strong></div><div class="report-card"><span>Estimated COGS</span><strong>TSh {{ number_format($data['cogs'],0) }}</strong></div><div class="report-card"><span>Gross Profit</span><strong>TSh {{ number_format($data['gross_profit'],0) }}</strong></div><div class="report-card"><span>Orders</span><strong>{{ $data['orders'] }}</strong></div><div class="report-card"><span>Paid Orders</span><strong>{{ $data['paid_orders'] }}</strong></div><div class="report-card"><span>Delivered</span><strong>{{ $data['delivered_orders'] }}</strong></div><div class="report-card"><span>New Customers</span><strong>{{ $data['new_customers'] }}</strong></div><div class="report-card"><span>Inbound Messages</span><strong>{{ $data['inbound_messages'] }}</strong></div></div>
    <div class="report-panel"><h2>Top products</h2><table class="report-table"><thead><tr><th>Product</th><th>Quantity</th><th>Revenue</th></tr></thead><tbody>@forelse($topProducts as $product)<tr><td>{{ $product->product_name }}</td><td>{{ $product->quantity }}</td><td>TSh {{ number_format($product->revenue,0) }}</td></tr>@empty<tr><td colspan="3">No sales data for this period.</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
